# Generated by Django 4.2.5 on 2023-11-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(default=None),
        ),
    ]
