# Generated by Django 4.2.5 on 2023-11-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
