# Generated by Django 4.2.5 on 2023-11-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_otp_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expiry_time',
        ),
    ]
