# Generated by Django 4.2.5 on 2023-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='upload_avatar/avatar.jpg', upload_to='upload_avatar'),
        ),
    ]
