# Generated by Django 4.2.5 on 2023-11-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_profile_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
