# Generated by Django 4.2.5 on 2023-11-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
