# Generated by Django 4.2.5 on 2023-11-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_customuser'),
        ('student', '0020_alter_profile_profile_img'),
    ]

    operations = [
    ]
