# Generated by Django 4.2.5 on 2023-11-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_merge_0002_customuser_0020_alter_profile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
