# Generated by Django 4.2.5 on 2023-11-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='student',
        ),
    ]
