"""
<<<<<<< HEAD
Django settings for myregister project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
=======
Django settings for Myregister project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, seef
>>>>>>> f4edfd9e7fb786eb5df392a54a82db2019aa53b2
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = 'django-insecure-%tubjfjrj#2!#3!p0+)et9257c7&s=y7m1lu^y%z)ndk*2b1p2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
=======
SECRET_KEY = 'django-insecure-^rr_p_$btf02w5f!%a93y6tf4npvpwv-!b^25b=r4r8t+ufhfd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False
>>>>>>> f4edfd9e7fb786eb5df392a54a82db2019aa53b2

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
=======
    'register'
>>>>>>> f4edfd9e7fb786eb5df392a54a82db2019aa53b2
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

<<<<<<< HEAD
ROOT_URLCONF = 'myregister.urls'
=======
ROOT_URLCONF = 'Myregister.urls'
>>>>>>> f4edfd9e7fb786eb5df392a54a82db2019aa53b2

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [],
=======
        'DIRS': ['Template'],
>>>>>>> f4edfd9e7fb786eb5df392a54a82db2019aa53b2
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

<<<<<<< HEAD
WSGI_APPLICATION = 'myregister.wsgi.application'
=======
WSGI_APPLICATION = 'Myregister.wsgi.application'
>>>>>>> f4edfd9e7fb786eb5df392a54a82db2019aa53b2


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
<<<<<<< HEAD
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


=======
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'register',
        'USER':'root',
        'HOST':'localhost',
        'PORT':'3306'

    }
}

>>>>>>> f4edfd9e7fb786eb5df392a54a82db2019aa53b2
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

<<<<<<< HEAD
STATIC_URL = 'static/'
=======
STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / "staticfiles"
>>>>>>> f4edfd9e7fb786eb5df392a54a82db2019aa53b2

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
