# Generated by Django 4.2.5 on 2023-10-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
