# Generated by Django 4.2.5 on 2023-11-05 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='pham', max_length=20)),
                ('last_name', models.CharField(default='manh', max_length=20)),
                ('desc', models.CharField(default='toilalaptrinhvien', max_length=200)),
                ('profile_img', models.ImageField(blank=True, default='media/avatar.jpg', upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
