# Generated by Django 4.2.5 on 2023-11-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_desc_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Hãy điền họ của bạn tại đây!', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Hãy điền tên của bạn tại đây!', max_length=50),
        ),
    ]
