# Generated by Django 4.2.5 on 2023-11-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_profile_desc_alter_profile_first_name_and_more'),
        ('userprofile', '0005_alter_profile_desc_alter_profile_first_name_and_more'),
    ]

    operations = [
    ]
