# Generated by Django 4.2.5 on 2023-11-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_merge_20231114_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
