# Generated by Django 4.2.6 on 2023-11-14 13:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('translater', models.CharField(max_length=200, null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('page', models.CharField(max_length=200, null=True)),
                ('Publication_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, default='book/images/Background_1.jpg', null=True, upload_to='book/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='book/pdfs/')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='author.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='category.category')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
