# Generated by Django 4.2.5 on 2023-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_publication_date_book_page_book_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='book/images/Background_1.jpg', null=True, upload_to='book/images/'),
        ),
    ]
