# Generated by Django 4.2.5 on 2023-11-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
