# Generated by Django 4.2.5 on 2023-11-14 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
