# Generated by Django 4.2.5 on 2023-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='author/images/'),
        ),
    ]
